// components/vue/App.vue
<template>
  <div>
    <h1>Vue</h1>
    <h4>cantidad {{ count }}</h4>
    <input type='button' v-on:click="handleIncrement" value="+"/>
    <input type='button' v-on:click="handleDecrement" value="-"/>
  </div>
</template>

<script>
    export default {
        name: 'App',
        data: () => ({
            count: window.myapp.counter,
        }),
        mounted() {
            window.addEventListener('onIncrement', () => {
                this.count = window.myapp.counter;
            })
            window.addEventListener('onDecrement', () => {
                this.count = window.myapp.counter;
            })
        },
        methods: {
            handleIncrement: () => {
                window.myapp.incrementor()
            },
            handleDecrement: () => {
                window.myapp.decrementor()
            }
        }
    }
</script>

// components/react/App.js
import React, { useEffect, useState } from 'react'

const App = () => {
  const [val, setVal] = useState(0)

  useEffect(() => {
    window.addEventListener('onIncrement', () => {
      setVal(window.myapp.counter)
    })
    window.addEventListener('onDecrement', () => {
      setVal(window.myapp.counter)
    })
  }, [])


return(
    <>
        <h1>React</h1>
        <p>cantidad {val}</p>
        <input type='button' onClick={() => window.myapp.incrementor()} value='+'></input>
        <input type='button' onClick={() => window.myapp.decrementor()} value='-'></input>
    </>
)
}
export default App
